
backend:
  name: github
  repo: sci6377/web-bachillerato-heroes
  branch: main
  auth_type: implicit
  app_id: Ov23lijAUN6icqf4St8d

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "config"
    label: "Configuración"
    files:
      - name: "general"
        label: "Información General"
        file: "data/config.json"
        fields:
          - { label: "Nombre de la Institución", name: "institution_name", widget: "string" }
          - { label: "CCT", name: "cct", widget: "string" }
          - { label: "Dirección", name: "address", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }

  - name: "testimonios"
    label: "Testimonios"
    files:
      - name: "testimonios"
        label: "Lista de Testimonios"
        file: "data/testimonios.json"
        fields:
          - name: "body"
            label: "Testimonios"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Testimonio", name: "texto", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "string", required: false }
